version: '{branch}-{build}'

install:
  - set PATH=C:\Ruby23\bin;%PATH%
  - bundle install
  - choco install chocolatey-core.extension
  - choco install -y nssm --pre
  - choco pack
  - choco install -y selenium --params "'/role:hub /service /port:4446 /autostart /log'" -d -s .
  - choco install -y googlechrome --ignorechecksum
  - choco install -y firefoxesr selenium-gecko-driver selenium-chrome-driver selenium-ie-driver
  - choco install -y selenium --params "'/role:node /hub:http://localhost:4446 /port:5557 /autostart /log'" -d -s . --force
  - ps: Start-Process C:\tools\selenium\node.cmd -PassThru

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
  - mvn clean test -Dtest="ChromeTest,FirefoxTest,IETest"

on_failure:
  - type C:\tools\selenium\hub.log
  - type C:\tools\selenium\node.log

artifacts:
  - path: '*.nupkg'
    name: Selenium
