install:
  - set PATH=C:\Ruby23\bin;%PATH%
  - bundle install
  - choco install firefox --version 46.0.1
  - choco install -y nssm --pre
  - choco install -y selenium --params "'/role:hub /service /autostart /port:4446'"

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake